name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "root_password"
          MYSQL_DATABASE: "domain_messages"
          MYSQL_USER: "username"
          MYSQL_PASSWORD: "password"
          MYSQL_ROOT_HOST: "0.0.0.0"
        ports:
          - "3306:3306"
      postgres:
        image: postgres:9.6-alpine
        env:
          POSTGRES_DB: "domain_messages"
          POSTGRES_USER: "username"
          POSTGRES_PASSWORD: "password"
        ports:
          - "5432:5432"

    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run database migrations
        run: |
          php tests/setup-mysql-schema.php
          php tests/setup-postgres-schema.php

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
